[general]
import = []
working_directory = "$HOME"
live_config_reload = true

[window]
padding = { x = 10, y = 2 }

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Regular" }
italic = { family = "FiraCode Nerd Font", style = "Regular" }
size = 12
builtin_box_drawing = true
offset = { x = 1, y = 2}
