spacing = 1
padding = 1
hide_ascii = true
prefer_small_ascii = true
separator = " => "
color = "Blue"


[box]
title = " Yjydist "
border = "rounded"
visible = true
x = 2
y = 2

[palette]
type = "Dark"
glyph = ""
visible = false

[bar]
glyph = "o"
symbol_open = '('
symbol_close = ')'
visible = false

[randomize]
key_color = false
separator_color = false

[key]
host = "Host"
kernel = "Kernel"
os = "OS"
machine = "Machine"
de = "DE"
wm = "WM"
distro = "Distro"
terminal = "Terminal"
shell = "Shell"
packages = "Packages"
uptime = "Uptime"
memory = "Memory"
battery = "Battery"
cpu = "CPU"
gpu = "GPU"
