source ./conf.d/monitor.conf # 显示器配置
source ./conf.d/default_app.conf # 默认应用配置
source ./conf.d/env.conf # 环境变量配置
source ./conf.d/auto_start.conf # 自启动配置
source ./conf.d/keybind.conf # 快捷键配置
source ./conf.d/appearance.conf # 外观配置
source ./conf.d/input.conf # 输入设备配置
source ./conf.d/rule.conf # 规则配置